### ISSUE TITLE
ImportError: cannot import name 'AmazonJob' from 'transcriptor'

### ISSUE THREAD

**Issue by bdougie** [kjaymiller/transcriptor#3]
# What happening?

Per our conversation earlier, I was able to copy your 4 line script from the README. Turns out my machine was using python 2, which I have updated.

**Comment by bdougie** [comment]
update: I am now using 3.8.5, but now stumped on why I am getting the follow error. cc/ @kjaymiller 

```sh
Traceback (most recent call last):
  File "transcribe.py", line 1, in <module>
    from transcriptor import amazon, AmazonJob
ImportError: cannot import name 'AmazonJob' from 'transcriptor' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transcriptor/__init__.py)
```

**Comment by kjaymiller** [comment]
in your import it should be `from transcriptor.amazon import AmazonJob`
